# Generated by Django 2.0.5 on 2018-06-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180610_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='master',
            field=models.BooleanField(default=False),
        ),
    ]
